security:
  encoders:
    App\Entity\User: bcrypt
      # use your user class name here
      App\Entity\User:
        # Use- native password encoder
        # This value auto-selects the best possible hashing algorithm
        # (i.e. Sodium when available).
        algorithm: auto

  providers:
    database_users:
      entity: { class: App\Entity\User, property: username }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      logout:
        path: logout
        target: acceuil
      guard:
        authenticators:
          - App\Security\LoginAuthenticator

  access_control:
    - { path: '^/admin', roles: ROLE_ADMIN }
    - { path: '^/proposals/add', roles: ROLE_USER }
    - { path: '^/ressources/new', roles: ROLE_USER }